/**
 * Memory Bank Generator
 * Genera archivos del Memory Bank a partir de las respuestas del wizard
 */

import { WIZARD_STEPS, WizardQuestion, calculateCompleteness } from './wizard-questions';

interface WizardAnswers {
  [questionId: string]: string | string[];
}

interface GeneratedFile {
  name: string;
  content: string;
}

interface GenerationResult {
  files: GeneratedFile[];
  completeness: number;
  missingCritical: string[];
}

// Plantillas base para cada archivo del Memory Bank
const FILE_TEMPLATES: Record<string, string> = {
  '01-PROJECT-OVERVIEW.md': `# Project Overview

## Purpose
{Purpose}

## Target Users
{Target Users}

## Key Features
{Key Features}

## Current Stage
{Current Stage}

## Quick Reference
- **Project Type**: {project_type}
- **Status**: {Current Stage}
- **Last Updated**: {date}
`,

  '02-ARCHITECTURE.md': `# Architecture

## Architecture Style
{Architecture Style}

## System Components
{components}

## Deployment
{Deployment}

## Data Storage
{Data Storage}

## External Services
{External Services}

## Data Flow
{data_flow}
`,

  '03-TECH-STACK.md': `# Tech Stack

## Frontend
{Frontend}

## Backend
{Backend}

## Styling
{Styling}

## State Management
{State Management}

## Testing
{Testing}

## Development Tools
- Package Manager: npm/pnpm/yarn
- Linting: ESLint
- Formatting: Prettier
`,

  '04-BUSINESS-LOGIC.md': `# Business Logic

## Business Rules
{Business Rules}

## User Roles
{User Roles}

## Main Workflows
{Main Workflows}

## Validations
{validations}

## Error Handling
{error_handling}
`,

  '05-CODING-STANDARDS.md': `# Coding Standards

## Naming Conventions
{Naming Conventions}

## File Structure
{File Structure}

## Design Patterns
{Design Patterns}

## Best Practices
- Use TypeScript for type safety
- Write meaningful variable names
- Comment complex logic
- Keep functions small and focused

## Code Review Guidelines
- Check for type safety
- Verify error handling
- Ensure consistent naming
- Review test coverage
`,

  '10-DESIGN-SYSTEM.md': `# Design System

## Status
{Status}

## Colors
{Colors}

### Primary Palette
{primary_colors}

### Semantic Colors
{semantic_colors}

## Typography
{Typography}

### Font Families
{fonts}

### Scale
{type_scale}

## Spacing
{spacing}

## Components
See 11-COMPONENT-LIBRARY.md for component documentation.
`,

  '11-COMPONENT-LIBRARY.md': `# Component Library

## Components
{Components}

## Component Status

| Component | Status | Documentation |
|-----------|--------|---------------|
{component_table}

## Usage Guidelines
{usage_guidelines}
`,

  'META-MEMORY-BANK.md': `# Memory Bank Meta

## Completeness Score
**{completeness}%** - {completeness_status}

## Last Updated
{date}

## Files in this Memory Bank

| File | Purpose | Status |
|------|---------|--------|
{file_table}

## How to Update
1. Edit the relevant .md file directly
2. Or ask the AI assistant to update specific sections
3. Keep information current as the project evolves

## Generated By
Project Wizard - Initial Setup
`
};

/**
 * Genera los archivos del Memory Bank a partir de las respuestas
 */
export function generateMemoryBank(answers: WizardAnswers): GenerationResult {
  const completeness = calculateCompleteness(answers);
  const missingCritical: string[] = [];
  const generatedFiles: GeneratedFile[] = [];

  // Agrupar respuestas por archivo
  const fileContents: Record<string, Record<string, string>> = {};

  for (const step of WIZARD_STEPS) {
    for (const question of step.questions) {
      const answer = answers[question.id];
      const fileName = question.memoryBankFile;
      const section = question.memoryBankSection;

      if (!fileContents[fileName]) {
        fileContents[fileName] = {};
      }

      if (answer) {
        const formattedAnswer = formatAnswer(answer, question);
        fileContents[fileName][section] = formattedAnswer;
      } else if (question.importance === 'critical') {
        missingCritical.push(question.question);
      }
    }
  }

  // Generar cada archivo usando las plantillas
  for (const [fileName, sections] of Object.entries(fileContents)) {
    const template = FILE_TEMPLATES[fileName];
    if (template) {
      let content = template;

      // Reemplazar secciones conocidas
      for (const [section, value] of Object.entries(sections)) {
        const placeholder = `{${section}}`;
        content = content.replace(placeholder, value || '_No especificado_');
      }

      // Limpiar placeholders no usados
      content = content.replace(/\{[^}]+\}/g, '_No especificado_');

      // Reemplazar fecha
      content = content.replace(/\{date\}/g, new Date().toISOString().split('T')[0]);

      generatedFiles.push({
        name: fileName,
        content
      });
    }
  }

  // Generar META file
  const metaContent = generateMetaFile(generatedFiles, completeness);
  generatedFiles.push({
    name: 'META-MEMORY-BANK.md',
    content: metaContent
  });

  return {
    files: generatedFiles,
    completeness,
    missingCritical
  };
}

/**
 * Formatea una respuesta según su tipo
 */
function formatAnswer(answer: string | string[], question: WizardQuestion): string {
  if (Array.isArray(answer)) {
    // Para multiselect, crear lista
    if (answer.length === 0) return '_No especificado_';
    return answer.map(item => `- ${item}`).join('\n');
  }

  // Para texto, formatear según el tipo
  const text = answer.trim();
  if (!text) return '_No especificado_';

  // Si tiene múltiples líneas o comas, formatear como lista
  if (text.includes('\n') || (text.includes(',') && question.type === 'textarea')) {
    const items = text.split(/[,\n]+/).map(s => s.trim()).filter(Boolean);
    if (items.length > 1) {
      return items.map(item => `- ${item}`).join('\n');
    }
  }

  return text;
}

/**
 * Genera el archivo META del Memory Bank
 */
function generateMetaFile(files: GeneratedFile[], completeness: number): string {
  const date = new Date().toISOString().split('T')[0];

  let status = 'Needs work';
  if (completeness >= 80) status = 'Excellent';
  else if (completeness >= 60) status = 'Good';
  else if (completeness >= 40) status = 'Basic';

  const fileTable = files
    .filter(f => f.name !== 'META-MEMORY-BANK.md')
    .map(f => {
      const purpose = getFilePurpose(f.name);
      const hasContent = !f.content.includes('_No especificado_') || f.content.length > 200;
      return `| ${f.name} | ${purpose} | ${hasContent ? '✅' : '⚠️'} |`;
    })
    .join('\n');

  return `# Memory Bank Meta

## Completeness Score
**${completeness}%** - ${status}

## Last Updated
${date}

## Files in this Memory Bank

| File | Purpose | Status |
|------|---------|--------|
${fileTable}

## How to Update
1. Edit the relevant .md file directly
2. Or ask the AI assistant to update specific sections
3. Keep information current as the project evolves

## Generated By
Project Wizard - Initial Setup
`;
}

/**
 * Obtiene el propósito de un archivo del Memory Bank
 */
function getFilePurpose(fileName: string): string {
  const purposes: Record<string, string> = {
    '01-PROJECT-OVERVIEW.md': 'Project vision and goals',
    '02-ARCHITECTURE.md': 'Technical architecture',
    '03-TECH-STACK.md': 'Technologies used',
    '04-BUSINESS-LOGIC.md': 'Business rules',
    '05-CODING-STANDARDS.md': 'Code conventions',
    '10-DESIGN-SYSTEM.md': 'Design tokens',
    '11-COMPONENT-LIBRARY.md': 'UI components'
  };
  return purposes[fileName] || 'Documentation';
}

/**
 * Genera un Memory Bank mínimo con información básica
 */
export function generateMinimalMemoryBank(projectName: string, description?: string): GeneratedFile[] {
  const date = new Date().toISOString().split('T')[0];

  return [
    {
      name: '01-PROJECT-OVERVIEW.md',
      content: `# Project Overview

## Purpose
${description || `${projectName} - A new project`}

## Target Users
_To be defined_

## Key Features
_To be defined_

## Current Stage
Development

## Quick Reference
- **Project Name**: ${projectName}
- **Created**: ${date}
`
    },
    {
      name: 'META-MEMORY-BANK.md',
      content: `# Memory Bank Meta

## Completeness Score
**10%** - Initial setup

## Last Updated
${date}

## Files in this Memory Bank

| File | Purpose | Status |
|------|---------|--------|
| 01-PROJECT-OVERVIEW.md | Project vision and goals | ⚠️ |

## How to Update
Use the Project Wizard to add more information, or edit files directly.

## Generated By
Quick Setup - Minimal Memory Bank
`
    }
  ];
}

/**
 * Combina respuestas del wizard con documentación subida
 */
export function mergeWithUploadedDocs(
  wizardResult: GenerationResult,
  uploadedContent: string,
  fileName: string
): GenerationResult {
  // Agregar el documento subido como archivo adicional
  const docFile: GeneratedFile = {
    name: `UPLOADED-${fileName}`,
    content: `# Uploaded Documentation

Source: ${fileName}

---

${uploadedContent}
`
  };

  return {
    ...wizardResult,
    files: [...wizardResult.files, docFile]
  };
}
